# Generated by Django 2.1.4 on 2018-12-22 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowlevelmanager',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialist', to='employee_server.Specialist'),
        ),
    ]
