# Generated by Django 2.1.4 on 2018-12-19 11:01

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employee_server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalmanager',
            name='department',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_server.Subdivision'),
        ),
        migrations.AddField(
            model_name='lowlevelmanager',
            name='department',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_server.Subdivision'),
        ),
        migrations.AddField(
            model_name='seniormanager',
            name='department',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_server.Subdivision'),
        ),
        migrations.AddField(
            model_name='topmanager',
            name='department',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_server.Subdivision'),
        ),
    ]
