# Generated by Django 2.1.4 on 2018-12-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media'),
        ),
    ]
