# Generated by Django 2.1.4 on 2018-12-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_server', '0002_auto_20181218_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='employment_date',
            field=models.DateField(default=None),
        ),
    ]
