# Generated by Django 2.1.4 on 2018-12-19 12:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employee_server', '0002_auto_20181219_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stockholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('patronymic_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('employment_date', models.DateField(default=None)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('department', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_server.Subdivision')),
                ('general_manager', models.ManyToManyField(related_name='general_manager', to='employee_server.GeneralManager')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stockholder', related_query_name='stockholder', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stockholder',
                'verbose_name_plural': 'Stockholders',
            },
        ),
    ]
