# Generated by Django 2.1.4 on 2018-12-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_server', '0003_stockholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='slug',
            field=models.SlugField(default=None, unique=True),
        ),
        migrations.AddField(
            model_name='subdivision',
            name='slug',
            field=models.SlugField(default=None),
        ),
        migrations.AlterUniqueTogether(
            name='subdivision',
            unique_together={('slug', 'parent')},
        ),
    ]
