# Generated by Django 2.1.4 on 2018-12-18 13:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_server', '0004_auto_20181218_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stockholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('patronymic_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('employment_date', models.DateField(default=None)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'verbose_name': 'Stockholder',
                'verbose_name_plural': 'Stockholders',
            },
        ),
        migrations.CreateModel(
            name='TopManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('patronymic_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('employment_date', models.DateField(default=None)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'verbose_name': 'Top Manager',
                'verbose_name_plural': 'Top Managers',
            },
        ),
        migrations.AlterModelOptions(
            name='subdivisionmanager',
            options={'verbose_name': 'Subdivision Manager', 'verbose_name_plural': 'Subdivision Managers'},
        ),
        migrations.AddField(
            model_name='topmanager',
            name='sub_manager',
            field=models.ManyToManyField(related_name='sub_manager', to='employee_server.SubdivisionManager'),
        ),
        migrations.AddField(
            model_name='topmanager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='topmanager', related_query_name='topmanager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockholder',
            name='top_manager',
            field=models.ManyToManyField(related_name='top_manager', to='employee_server.TopManager'),
        ),
        migrations.AddField(
            model_name='stockholder',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stockholder', related_query_name='stockholder', to=settings.AUTH_USER_MODEL),
        ),
    ]
