# Generated by Django 2.1.4 on 2018-12-18 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_server', '0005_auto_20181218_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='employee_server.Manager', verbose_name='Родитель'),
        ),
    ]
