# Generated by Django 2.1.4 on 2018-12-18 15:53

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employee_server', '0006_manager_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='employee_server.Staff')),
            ],
            options={
                'verbose_name_plural': 'staffs',
            },
        ),
        migrations.RemoveField(
            model_name='manager',
            name='parent',
        ),
        migrations.AddField(
            model_name='employee',
            name='staff',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_server.Staff'),
        ),
        migrations.AlterUniqueTogether(
            name='staff',
            unique_together={('parent',)},
        ),
    ]
